/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/jrT6uI586Po
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Tenor_Sans } from 'next/font/google'
import { Cormorant_Garamond } from 'next/font/google'

tenor_sans({
  subsets: ['latin'],
  display: 'swap',
})

cormorant_garamond({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
"use client";
import Header from "./Header";
import Footer from "./Footer";
import Hero from "./Hero";

export function FinalComponent() {
  return (
    <div className="flex flex-col min-h-screen bg-background">
      <Header />
      <Hero />
      <Footer />
    </div>
  );
}
